/// <reference types="@cloudflare/workers-types" />
// Generated by `wrangler types --env-interface CloudflareEnv worker-configuration.d.ts`
// Do not edit manually.

interface CloudflareEnv {
  ASSETS: Fetcher;
  PARTY_ROOM: DurableObjectNamespace<import("./durable-objects/party-room").PartyRoomDO>;
}
